language: ruby
dist: trusty
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler
bundler_args: --jobs=2

before_install:
  - gem update --system

script:
  - bundle exec rake spec
